GET http://localhost:9999/clientes/1/extrato
content-type: application/json

###

POST http://localhost:9999/clientes/6/transacoes
content-type: application/json

{
    "valor": "1",
    "descricao": "a",
    "tipo": "d"
}

###

POST http://localhost:9999/clientes/2/transacoes
content-type: application/json

{
    "valor": "12",
    "descricao": "a",
    "tipo": "c"
}